FROM alpine:3.6

ADD . /go-ethereum
RUN \
  apk add --update git go make gcc musl-dev linux-headers && \
  (cd go-ethereum && make geth)                           && \
  cp go-ethereum/build/bin/geth /usr/local/bin/           && \
  apk del git go make gcc musl-dev linux-headers          && \
  geth init ./go-ethereum/rinkeby.json			  && \
  rm -rf /go-ethereum && rm -rf /var/cache/apk/*	 

EXPOSE 8545
EXPOSE 30303
EXPOSE 30303/udp

#uses rinkeby testnet, default ports
ENTRYPOINT geth --networkid=4 --fast --cache 2048 --rpc --rpcapi="db,eth,net,web3,personal,web3,admin,,txpool,miner" --mine --minerthreads 2 --rpcaddr "0.0.0.0" --verbosity 4
