FROM alpine:3.6

ADD . /go-ethereum
RUN \
  apk add --update git go make gcc musl-dev linux-headers && \
  cp go-ethereum/private/boot.key ~	  		  && \
  cp go-ethereum/private/genesis.json  ~                  && \    
  (cd go-ethereum && make geth)                           && \
  cp go-ethereum/build/bin/geth /usr/local/bin/           && \
  apk del git go make gcc musl-dev linux-headers          && \
  geth init ./go-ethereum/private/genesis.json		  && \
  cp go-ethereum/private/keystore -rf /root/.ethereum/    && \
  rm -rf /go-ethereum && rm -rf /var/cache/apk/*	 

EXPOSE 8545
EXPOSE 30303
EXPOSE 30303/udp

# ENV BOOTNODE : ip of bootnode
ENTRYPOINT geth -verbosity 4 --etherbase "0xa7129ba8dffd19869ec6d408e9866d43935c5099" --ipcdisable --port 30303 --rpcport 8545 -rpc --rpcapi="db,eth,net,web3,personal,web3,admin,txpool,miner" --mine --minerthreads 2  --rpcaddr "0.0.0.0"  --networkid=990099 --nodiscover --bootnodes enode://74b13cc21a2204fedd54712c96f5c3586539886969821871d93612ea94e8681f54a6e3aedc3f819c25b66cf225c66e3ad47d5e0d1b7e723596f2a583e700bc86@$BOOTNODE:30301
